import React from 'react';
import FoodList from '../components/FoodList';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "AMT-Kitchen",
  description: "Generated by Abdullah Al Mubin",
};
const Home: React.FC = () => {
  return (
    <div className="w-11/12 mx-auto">
      <FoodList />
    </div>
  );
};

export default Home;
